### ISSUE TITLE
Potential v2 changes

### ISSUE THREAD

**Issue by carver** [ApeWorX/py-trie#85]
Would like to make some backwards-incompatible changes. For example:

- [x] Change `MissingTrieNode` exception to stop subclassing from `KeyError` #98
- [ ] Default trie to be immutable, where every change spits out a new root hash, and list of nodes to change, but doesn't affect the original trie. (and stop tracking the root hash as a property of the trie) -- This would be cool, but might not make it into v2
- [x] remove `trie.sync` #100 
- [x] remove `trie.Trie` #100 
- [x] Drop py3.5 support #97 
- [x] return `HexaryTrieNode` from `HexaryTrie.root_node` #103 
- [ ] Move `trie.utils` to `trie._utils`
- [x] Drop pypy spport (to enable the faster, rust-based py-rlp) #118 

Not incompatible, but important changes:
- [ ] Publicize some methods that seem to be useful tools, like `key_starts_with` (See https://github.com/ethereum/trinity/pull/1883#discussion_r454750977 )
- [ ] Unify imports so that we can do `from trie import HexaryTrieFog, NodeIterator` etc.

Surely there are others, just wanted to start a running list.

**Comment by pipermerriam** [comment]
:+1: immutability

**Comment by carver** [comment]
Drop support for `from trie import Trie` (which is an alias for `HexaryTrie`)

**Comment by carver** [comment]
Drop deprecated `HexaryTrieSync`
